#!/usr/bin/env python2

import kurt, sys
import xml.etree.ElementTree

if len(sys.argv) < 2:
    sys.stderr.write("Usage: %s infile.xml outfile.sb2\n" % sys.argv[0])
    sys.exit()

snap_project = xml.etree.ElementTree.parse(sys.argv[1])
snap_project_root = snap_project.getroot()

print "Snap! project generated by \"%s\"" % snap_project_root.attrib["app"]

scratch_project = kurt.Project()

for child in snap_project_root:
    if child.tag == "notes":
        # set project notes
        if child.text != None:
            scratch_project.notes = child.text

scratch_project.save(sys.argv[2])
